package com.android.meetingninja;

import java.util.Locale;

import android.app.ActionBar;
import android.app.FragmentTransaction;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.view.ViewPager;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;

import com.android.meetingninja.meetings.MeetingsFragment;
import com.android.meetingninja.notes.CreateNoteActivity;
import com.android.meetingninja.notes.NotesFragment;
import com.android.meetingninja.tasks.TasksFragment;
import com.android.meetingninja.user.LoginActivity;
import com.android.meetingninja.user.ProfileFragment;
import com.android.meetingninja.user.SessionManager;

/**
 * Main Window displaying tabs for meetings and notes. Mostly autogenerated by
 * Eclipse.
 * 
 * @author moorejm
 * 
 */
public class MainActivity extends FragmentActivity implements
		ActionBar.TabListener {

	/**
	 * The {@link android.support.v4.view.PagerAdapter} that will provide
	 * fragments for each of the sections. We use a
	 * {@link android.support.v4.app.FragmentPagerAdapter} derivative, which
	 * will keep every loaded fragment in memory. If this becomes too memory
	 * intensive, it may be best to switch to a
	 * {@link android.support.v4.app.FragmentStatePagerAdapter}.
	 */
	SectionsPagerAdapter mSectionsPagerAdapter;

	/**
	 * The {@link ViewPager} that will host the section contents.
	 */
	ViewPager mViewPager;

	public static final int PROFILE_FRAGMENT = 0;
	public static final int MEETINGS_FRAGMENT = 1;
	public static final int NOTES_FRAGMENT = 2;
	public static final int TASKS_FRAGMENT = 3;

	public static String username;
	public String fragment;
	public Intent callingIntent;
	private ActionBar actionBar;
	private static ProfileFragment prof = null;
	private static MeetingsFragment meetingsFrag;
	private static NotesFragment notesFrag;
	private static TasksFragment tasksFrag;
	private SessionManager session;
	private String[] tabNames = new String[] { "Profile", "Meetings", "Notes",
			"Tasks" };

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		session = new SessionManager(getApplicationContext());

		// Check if logged in
		session.checkLogin();

		// Else continue
		setContentView(R.layout.activity_main);
		setupActionBar();
		username = session.getUserDetails().get(SessionManager.USER);

	}

	private void setupActionBar() {
		// Set up the action bar.

		actionBar = getActionBar();
		actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

		// Create the adapter that will return a fragment for each of the three
		// primary sections of the app.
		mSectionsPagerAdapter = new SectionsPagerAdapter(
				getSupportFragmentManager());

		// Set up the ViewPager with the sections adapter.
		mViewPager = (ViewPager) findViewById(R.id.pager);
		mViewPager.setAdapter(mSectionsPagerAdapter);

		// When swiping between different sections, select the corresponding
		// tab. We can also use ActionBar.Tab#select() to do this if we have
		// a reference to the Tab.
		mViewPager
				.setOnPageChangeListener(new ViewPager.SimpleOnPageChangeListener() {
					@Override
					public void onPageSelected(int position) {
						actionBar.setSelectedNavigationItem(position);
					}
				});

		// Setup the tabs here
		Locale l = Locale.getDefault();

		// For each of the sections in the app, add a tab to the action bar.
		for (int i = 0; i < mSectionsPagerAdapter.getCount(); i++) {
			// Create a tab with text corresponding to the page title defined by
			// the adapter. Also specify this Activity object, which implements
			// the TabListener interface, as the callback (listener) for when
			// this tab is selected.
			ActionBar.Tab tab = actionBar.newTab();
			tab.setText(tabNames[i].toUpperCase(l));
			actionBar.addTab(tab.setTabListener(this));
		}

		// Get the extras from the calling intent
		username = getIntent().getStringExtra(LoginActivity.EXTRA_EMAIL);

		if (getIntent().hasExtra("Fragment")
				&& getIntent().getStringExtra("Fragment").compareToIgnoreCase(
						"notes") == 0) {
			Log.d("GET_INTENT", getIntent().getStringExtra("Fragment"));
			callingIntent = getIntent();

			if (callingIntent.getStringExtra("TypeL") != null)
				if (callingIntent.getStringExtra("TypeL").equals("Create")) {
					notesFrag.rebuildListView();
					return;
				}

			notesFrag.rebuildListView();

		}
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		// Handle presses on the action bar items
		switch (item.getItemId()) {
		case R.id.action_refresh:
			switch (mViewPager.getCurrentItem()) {
			case (MEETINGS_FRAGMENT):
				Toast.makeText(this, "Refreshing Meetings", Toast.LENGTH_SHORT)
						.show();
				meetingsFrag.refreshMeetings();
				return true;
			case (NOTES_FRAGMENT):
				Toast.makeText(this, "Refreshing Notes", Toast.LENGTH_SHORT)
						.show();
				return true;
			default:
				return super.onOptionsItemSelected(item);
			}

		case R.id.action_new_meeting:
			meetingsFrag.createMeeting();
			return true;
		case R.id.action_new_note:
			Toast.makeText(this, "Create a note", Toast.LENGTH_SHORT).show();
			Intent createNote = new Intent(this, CreateNoteActivity.class);
			startActivity(createNote);
			// notesFrag.createNewNote();
			return true;
		case R.id.action_logout:
			session.logoutUser();
			return true;
		default:
			return super.onOptionsItemSelected(item);
		}

	}

	@Override
	public void onTabSelected(ActionBar.Tab tab,
			FragmentTransaction fragmentTransaction) {
		// When the given tab is selected, switch to the corresponding page in
		// the ViewPager.
		mViewPager.setCurrentItem(tab.getPosition());
	}

	@Override
	public void onTabUnselected(ActionBar.Tab tab,
			FragmentTransaction fragmentTransaction) {
	}

	@Override
	public void onTabReselected(ActionBar.Tab tab,
			FragmentTransaction fragmentTransaction) {
	}

	/**
	 * A {@link FragmentPagerAdapter} that returns a fragment corresponding to
	 * one of the sections/tabs/pages.
	 */
	public class SectionsPagerAdapter extends FragmentPagerAdapter {

		public SectionsPagerAdapter(FragmentManager fm) {
			super(fm);
		}

		@Override
		public Fragment getItem(int position) {
			// getItem is called to instantiate the fragment for the given page.
			// Return a Fragment depending on the tab position
			Fragment frag = null;
			Bundle args = new Bundle();
			switch (position) {
			case (PROFILE_FRAGMENT):
				prof = new ProfileFragment();
				return prof;
			case (MEETINGS_FRAGMENT):
				meetingsFrag = new MeetingsFragment();
				return meetingsFrag;
			case (NOTES_FRAGMENT):
				notesFrag = new NotesFragment();
				return notesFrag;
			case (TASKS_FRAGMENT):
				tasksFrag = new TasksFragment();
				return tasksFrag;
			default:
				return frag;
			}
		}

		@Override
		public int getCount() {
			// Show 4 total pages.
			return 4;
		}

		@Override
		public CharSequence getPageTitle(int position) {
			Locale l = Locale.getDefault();
			if (position >= 0 && position < tabNames.length) {
				return tabNames[position].toUpperCase(l);
			}
			return null;
		}
	}

}
