package objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
// Generated by : http://www.jsonschema2pojo.org/
@JsonPropertyOrder({ "commentID", "commentBy", "content" })
public class Comment {
	@JsonProperty("commentID")
	private String commentID;
	@JsonProperty("commentBy")
	private String commentBy;
	@JsonProperty("content")
	private String content;
	
	public Comment() {
		// Required empty constructor
	}

	@JsonProperty("commentID")
	public String getID() {
		return commentID;
	}

	@JsonProperty("commentID")
	public void setID(String id) {
		int testInt = Integer.parseInt(id);
		setID(testInt);
	}

	@JsonProperty("commentID")
	public void setID(int id) {
		this.commentID = Integer.toString(id);
	}

	@JsonProperty("commentBy")
	public String getCommentBy() {
		return commentBy;
	}

	@JsonProperty("commentBy")
	public void setCommentBy(String commentBy) {
		this.commentBy = commentBy;
	}

	@JsonProperty("content")
	public String getContent() {
		return content;
	}

	@JsonProperty("content")
	public void setContent(String content) {
		this.content = content;
	}

}
