package objects;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import android.os.Parcel;
import android.os.Parcelable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.databind.JsonNode;

@JsonInclude(JsonInclude.Include.NON_NULL)
// Generated by http://www.jsonschema2pojo.org/
@JsonPropertyOrder({ "meetingID", "title", "location", "datetime",
		"endDatetime", "description", "attendance" })
public class Meeting extends Event implements Parcelable, IJSONObject<Meeting> {
	private String meetingID;
	protected String location;

	private List<String> attendance = new ArrayList<String>();

	private enum Attendance_Status {
		YES(1), MAYBE(0), NO(-1), NO_RESPONSE(-2);

		Attendance_Status(int stat) {
		}

		@Override
		public String toString() {
			switch (this) {
			case YES:
				return "Yes";
			case NO:
				return "No";
			case MAYBE:
				return "Maybe";
			default:
				break;
			}
			return "No Repsonse";
		}
	}

	public Meeting() {
		// Required empty constructor
		setStartTime(0L);
		setEndTime(1L);
	}

	public Meeting(Parcel in) {
		readFromParcel(in);
	}

	public Meeting(Meeting copyMeeting) {
		setID(copyMeeting.getID());
		setTitle(copyMeeting.getTitle());
		setLocation(copyMeeting.getLocation());
		setStartTime(copyMeeting.getStartTime());
		setEndTime(copyMeeting.getEndTime());
		setDescription(copyMeeting.getDescription());
		setAttendance(copyMeeting.getAttendance());
	}
	
	public Meeting(JsonNode node) {
		
	}

	@Override
	public String getID() {
		return this.meetingID;
	}

	@Override
	public void setID(int id) {
		this.meetingID = Integer.toString(id);

	}

	public List<String> getAttendance() {
		return attendance;
	}

	public String getLocation() {
		return (location != null && !location.isEmpty()) ? location : "";
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public void setAttendance(List<String> attendance) {
		this.attendance = attendance;
	}

	public void addAttendee(String userID) {
		// this.attendance.add(new AttendeeWrapper(userID,
		// Attendance_Status.YES));
		this.attendance.add(userID);
	}

	@Override
	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString(getID());
		dest.writeString(getTitle());
		dest.writeString(getLocation());
		dest.writeString(getStartTime());
		dest.writeString(getEndTime());
		dest.writeString(getDescription());
		dest.writeList(getAttendance());

	}

	private void readFromParcel(Parcel in) {
		meetingID = in.readString();
		title = in.readString();
		location = in.readString();
		startTime = in.readString();
		endTime = in.readString();
		description = in.readString();
		attendance = (ArrayList<String>) in.readArrayList(String.class
				.getClassLoader());
	}

	public static final Parcelable.Creator<Meeting> CREATOR = new Parcelable.Creator<Meeting>() {

		public Meeting createFromParcel(Parcel in) {
			return new Meeting(in);
		}

		public Meeting[] newArray(int size) {
			return new Meeting[size];
		}

	};

	public class AttendeeWrapper {
		private String _id;
		private Meeting.Attendance_Status _attending;

		public AttendeeWrapper() {
			// empty
		}

		public AttendeeWrapper(String userID, Attendance_Status attending) {
			_id = userID;
			_attending = attending;
		}

		public boolean isAttending() {
			switch (_attending) {
			case YES:
			case MAYBE:
			case NO_RESPONSE:
				return true;
			case NO:
				return false;
			}
			return false;
		}

		public String getID() {
			return _id;
		}

	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Meeting [meetingID=");
		builder.append(meetingID);
		builder.append(", title=");
		builder.append(title);
		builder.append(", location=");
		builder.append(location);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

	@Override
	public JsonNode toJSON() throws JsonGenerationException, IOException {
		// TODO Auto-generated method stub
		return null;
	}

}
