package objects;

import java.util.ArrayList;
import java.util.List;

import android.os.Parcel;
import android.os.Parcelable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
// Generated by http://www.jsonschema2pojo.org/
@JsonPropertyOrder({ "projectID", "projectTitle", "meetings", "notes",
		"members" })
public class Project implements Comparable<Project>, Parcelable{

	@JsonProperty("projectID")
	private String projectID;
	@JsonProperty("projectTitle")
	private String projectTitle;
	@JsonProperty("meetings")
	private List<Meeting> meetings = new ArrayList<Meeting>();
	@JsonProperty("notes")
	private List<Note> notes = new ArrayList<Note>();
	@JsonProperty("members")
	private List<User> members = new ArrayList<User>();
	
	public Project(Parcel in){
		readFromParcel(in);
	}

	public Project() {
		// do nothign
	}

	@JsonProperty("projectID")
	public String getProjectID() {
		return projectID;
	}

	@JsonProperty("projectID")
	public void setProjectID(String projectID) {
		this.projectID = projectID;
	}

	@JsonProperty("projectTitle")
	public String getProjectTitle() {
		return projectTitle;
	}

	@JsonProperty("projectTitle")
	public void setProjectTitle(String projectTitle) {
		this.projectTitle = projectTitle;
	}

	@JsonProperty("meetings")
	public List<Meeting> getMeetings() {
		return meetings;
	}

	@JsonProperty("meetings")
	public void setMeetings(List<Meeting> meetings) {
		this.meetings = meetings;
	}

	@JsonProperty("notes")
	public List<Note> getNotes() {
		return notes;
	}

	@JsonProperty("notes")
	public void setNotes(List<Note> notes) {
		this.notes = notes;
	}

	@JsonProperty("members")
	public List<User> getMembers() {
		return members;
	}

	@JsonProperty("members")
	public void setMembers(List<User> members) {
		this.members = members;
	}
	
	public void addMember(User user){
		this.members.add(user);
	}
	
	public void addMeeting(Meeting meeting){
		this.meetings.add(meeting);
	}
	
	public void addNote(Note note){
		this.notes.add(note);
	}
	public int compareTo(Project another) {
		if (another == null) {
			return 1;
		}
		if (another instanceof Project) {
			return compareTo((Project) another);
		}
		return this.getProjectTitle().compareTo(another.getProjectTitle());
	}

	@Override
	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	public static final Parcelable.Creator<Project> CREATOR = new Parcelable.Creator<Project>() {

		@Override
		public Project createFromParcel(Parcel in) {
			return new Project(in);
		}

		@Override
		public Project[] newArray(int size) {
			return new Project[size];
		}

	};
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		// TODO Auto-generated method stub
		dest.writeString(getProjectID());
		dest.writeString(getProjectTitle());
		dest.writeList(getMeetings());
		dest.writeList(getNotes());
		dest.writeList(getMembers());
		
	}
	public void readFromParcel(Parcel in){
		projectID = in.readString();
		projectTitle = in.readString();
		meetings = in.readArrayList(Meeting.class.getClassLoader());
		notes = in.readArrayList(Note.class.getClassLoader());
		members = in.readArrayList(User.class.getClassLoader());
	}

}
